// comment.interface.ts
export interface IComment {
    _id?: string; // Optional because it will be generated by MongoDB
    post: string; // ID of the post the comment belongs to
    author: string; // ID of the user who made the comment
    content: string; // The comment text
    createdAt?: Date; // Optional, will be set by MongoDB
    updatedAt?: Date; // Optional, will be set by MongoDB
  }
  